function [temperature,shortwave] = importW(fileName,t)
% importW imports and processes weather data from an xlsx file
% generated by ResStock.
%
% Input:
%   fileName, the name of the ResStock weather file.
%   t, the datetime span.
%
% Output:
%   temperature, the outdoor temperature in C
%   shortwave, the global solar shortwave irradiance on a horizontal surface in kW/m^2


% import raw data
opts = detectImportOptions(fileName);
opts.PreserveVariableNames = 1;
weatherData = readtable(fileName,opts);

% extract data and ensure year format is YYYY
timeStamp = weatherData{:,1}; % time stamp
if timeStamp(1).Year < 2000, timeStamp.Year = timeStamp.Year + 2000; end

temperature = weatherData{:,2}; % outdoor air temperature, C
shortwave = weatherData{:,6}/1000; % global horizontal shortwave irradiance, kW/m^2

% fill any missing data
temperature = fillmissing(temperature,'linear');
shortwave = fillmissing(shortwave,'linear');

% pack the data into a timetable object
TT = timetable(timeStamp,temperature,shortwave);

% retime to the desired time steps
TT = retime(TT,t);
temperature = TT{:,1};
shortwave = TT{:,2};

% fill any missing data again
temperature = fillmissing(temperature,'previous');
shortwave = fillmissing(shortwave,'previous');

end

